### ISSUE TITLE
Long paths on Windows

### ISSUE THREAD

**Issue by OronDF343** [shadowmoose/RedditDownloader#19] opened 2018-01-25 21:33 UTC
RedditDownloader fails to download any posts that would result in a file being created that has a full path of over 260 characters in length on Windows 7.

While this issue is entirely Microsoft's fault, I would still appreciate a workaround. Either some way of shortening names or using APIs that allow the use of long paths, whatever works.

**Comment by shadowmoose** [comment] 2018-01-26 03:08
Interesting - I thought I had fixed this. I'll have to make a test post to figure this one out. 

Looking at my previous fix, I see where it's probably going wrong. I'll roll this into the next update.

**Comment by shadowmoose** [comment] 2018-01-26 22:48
**Update:** I've pushed an update that will probably fix this issue, but it will need cross-platform tests created before it makes a full release. 

I'll need run some further checks to be sure it's not breaking things, but if you're looking for a faster fix, any release as of bf70e94 should be stable, and have it implemented.

**Comment by GreysenEvans** [comment] 2018-02-20 07:23
I have been having some issues as well that may be due to this.

One thing that I have noticed is that some downloaded media will be written one directory too high. I've also been unable to delete, copy, or move any user folder anywhere other than where they were originally written without getting an error from Windows.

I'll have a look at your fix and see if it helps.

**Comment by shadowmoose** [comment] 2018-02-20 18:28
A fix for filename length exists, and will be rolled into the next release. You can test it on the current branch, though the code there may not be entirely stable.

@GreysenEvans 
As far as being unable to move/rename/delete folders, see the issue (and fix for it) I've opened here (#20). It's an annoying Windows bug I wasn't aware of.  I actually stumbled on it myself a few days ago, and there's already a patch for that bug built in to the Threading test branch. As soon as that branch is stable, I'll be rolling it all out to be sure this issue doesn't grow in the future.

**Comment by shadowmoose** [comment] 2018-02-21 09:28
@GreysenEvans I noticed I missed the first part of your post. Do you have an example Post and output pattern you use, that you know can cause this issue? That's a strange one.

**Comment by GreysenEvans** [comment] 2018-02-28 06:50
Hey, @shadowmoose.

Sorry it took me so long to respond, but I've been trying to figure out if there was a pattern that might be causing this issue, and I think I've found it.

The files that were been placed a directory too high were always being renamed to the poster's username, along with an iterative number if there was already one or more files already there.

**For example:**
```
username.jpg
username . 2 .jpg
username . 3 .jpg
```

I used KarmaDecay to find out what the original posts were, since the titles had been overwritten.

It seems that **when a post has one or more emoji in it's title**, RedditDownloader doesn't know what to do, so it renames the file to the poster's username and places it one directory too high.

**Comment by shadowmoose** [comment] 2018-02-28 07:03
Strange. Are you using the stock pattern for file output, or a custom one? If it's custom, I'd appreciate if you could share it so I can run tests. 

I'll dig deeper and see why special chars may be interfering, but they really should be getting filtered out, so I'm thinking there may be an error happening further upstream when handling Posts.

**Comment by GreysenEvans** [comment] 2018-02-28 07:13
@shadowmoose

It's custom:
```
"base_dir": "A:/reddit.com/",
"file_name_pattern": "[title]",
"subdir_pattern": "/u/[author]/"
```

**Comment by shadowmoose** [comment] 2018-02-28 07:17
@GreysenEvans Thanks, I'll try it out and hunt down the issue. You're using the latest release instead of the latest branch changes, right? I'm thinking this may be solved in the latest branch, but I'll verify it is.

**Comment by GreysenEvans** [comment] 2018-03-01 02:39
@shadowmoose This issue was present on release 1.52 I believe. I haven't tested it yet on the latest release.

**Comment by shadowmoose** [comment] 2018-04-25 06:41
This should be resolved as of the 2.0 release. If it isn't, let me know.

**Comment by GreysenEvans** [comment] 2018-04-26 00:59
@shadowmoose The Emoji title issue appears to still be present in release 2.0.

The new threading feature is absolutely fantastic, by the way. Thank you for implementing a solution to the long wait times without even being asked to.

**Comment by shadowmoose** [comment] 2018-04-26 01:24
Hey @GreysenEvans , no problem. It's interesting that bug's still around. Do you have an example title (or link to a post) that you've noticed the issue on? All post inputs are heavily sanitized, so this problem is eluding me in my testing environment.

**Comment by GreysenEvans** [comment] 2018-04-26 02:11
@shadowmoose I think I've figured it out. The bug occurs when I try to download a post with _only_ Emoji in it's title.

I scrolled down the front page for a while to find an example to test my idea:
https://old.reddit.com/r/BikiniBottomTwitter/comments/8euw8h/_/

To conduct the test I set up r/BikiniBottomTwitter as a source and grabbed the top 2 'hot' posts in order to get that one, and the bug did indeed occur.

Sorry to keep you running around in circles for this bug. I don't believe that this is a problem when using RedditDownloader on a file system with Emoji support (such as Ext4), but I don't know how you would fix it in NTFS.

**Comment by shadowmoose** [comment] 2018-04-26 02:28
You actually just raised an interesting bug that I'll need to address; RMD could occasionally strip *all* characters from an inserted variable, if none of the characters were "valid". That's an interesting one. I'll have to add a default value to use there, if a variable ends up empty.

Thanks for chasing that down. It has potentially interesting (and bad) edge-cases, so I'll roll out a fix for that soon.

**Comment by GreysenEvans** [comment] 2018-04-26 02:40
@shadowmoose Perhaps you could just shoehorn in support for Emoji in titles?

I found out that since NTFS has full Unicode support, it should be able to display Emoji in filenames.
https://msdn.microsoft.com/en-us/library/windows/desktop/dd317748(v=vs.85).aspx

**Comment by GreysenEvans** [comment] 2018-04-26 02:44
@shadowmoose 

The Unicode website list Windows as a compatible operating system:
https://unicode.org/emoji/format.html#col-vendor

I can also copy and paste Emoji into filenames and rename them to Emoji:
https://unicode.org/emoji/charts/full-emoji-list.html

**Comment by shadowmoose** [comment] 2018-04-26 02:58
@GreysenEvans It gets tricky supporting extra characters, as I want to target out-of-the-box support for as many systems as possible. 

I agree that it would be nice to allow as many characters as possible though. I need to do some research here to figure out what the best solution can be for this. If I can think of a clever way to do so, I'll add support for as much as I can.

**Comment by GreysenEvans** [comment] 2018-04-26 03:15
@shadowmoose 

**APFS** (MacOS High Sierra and later), **HFS** (MacOS earlier than High Sierra), **NTFS** (Windows), and all versions of **Ext** (Linux) appear to support Emoji in filenames. 

Perhaps you could add an optional flag to disable Emoji in outputs, similar to youtube-dl's 
_--restrict-filenames_?

**Comment by shadowmoose** [comment] 2018-04-26 03:38
@GreysenEvans As cross-platform filename sanitizing gets pretty crazy fast, I'm testing bringing in an external library to help out. 

This should allow more characters in filenames through, assuming they're valid. I have yet to test it with emoji support - as I'm away from my usual developing setup - but if you feel like it, the Master branch should be running with this new library. Just be sure to rerun ```pip install -r requirements.txt``` if you do.

At any rate, I'm going to have to rewrite some tests to bring in more complex post names to help work on this, before I can push for full support.

**Comment by GreysenEvans** [comment] 2018-04-26 03:51
@shadowmoose 

Issue confirmed fixed as of 31bf4fd6b6cc860a6df3af5edf5b48a95fb682a3.

Thank you for your effort in resolving this, as well as in implementing threading.

**Comment by shadowmoose** [comment] 2018-04-26 04:02
@GreysenEvans Perfect! Thanks for the assistance.

**Comment by shadowmoose** [comment] 2018-04-28 03:57
The fix has, finally, been rolled out.

**Closed by shadowmoose** 2018-04-28 03:57 UTC
Labels: bug
