### ISSUE TITLE
Downloaders get locked until RMD is restarted

### ISSUE THREAD

**Issue by Test1049** [shadowmoose/RedditDownloader#87] opened 2019-11-06 22:12 UTC
Downloaders or Deduplication will (seemingly at random) seize up and not do anything until RMD is completely restarted. When it does this, the console reports an error.
It says:

> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
> [SQL: UPDATE files SET path=?, downloaded=? WHERE files.id = ?]
> [parameters: ('image.png', 1, 12757)]
> (Background on this error at: http://sqlalche.me/e/e3q8)

 - OS: Windows 10 Pro
 - RMD Version: 3.0.0

Apologies if this problem exists between the keyboard and the chair.

**Comment by shadowmoose** [comment] 2019-11-07 00:46
Thanks for reporting the bug. This is probably the same issue as #78.

It seems like I'm going to have to spend a while digging into this one - it's not an issue that's reproducible on any of the (multi-platform) testing setups RMD uses.

To help replicate this - are the files RMD downloads on your runs generally larger files (like videos, etc), albums, or just individual smaller files like single images? Are there any specific Source or Media types, or even websites, that are prevalent? Is RMD saving to an SSD, or an HDD?

Any information you don't mind sharing would be very helpful in figuring this out. I need to be able to duplicate this bug in a test environment before I can fix it.

**Comment by Test1049** [comment] 2019-11-07 09:33
I'll start testing myself to try to see what's causing this error. RMD is on and is saving all files to an HDD.

**Comment by xatnight** [comment] 2019-11-08 18:18
I'm having the same issue. It worked fine before for around 160k files but after deciding to start all over again I get the SQL error quite often. I downloaded the files with a 3.0 version from mid October (I think 17th or something) and I decided to start anew with the current 3.0 version a few days ago. Files are usually images with some small webms and gifs here and there. Most used website is probably imgur. Windows 10 Pro, 16gigs RAM, i7 4790k, saving to a SSD with 5 threads (used 8 before without any problems). Do you need anything else?

**Comment by shadowmoose** [comment] 2019-11-08 23:50
@xatnight Thanks for contributing some details. I'll take a look. 

I have a theory about Python SQLite's performance when under heavy concurrent access. it may be causing this issue, and if so, I can fix it with a bit of work around the DB transactions.

I'll chime in again once I've tested a new approach. In the meanwhile, it's possible that running RMD single-threaded (with deduplication off) might be enough to make things work, albeit at a much slower rate.

**Comment by shadowmoose** [comment] 2019-11-09 02:38
Update: I've set up a test branch with some more database locking. If anybody wants to test it before it gets merged, feel free to download it here: 

https://github.com/shadowmoose/RedditDownloader/archive/proc-shared-memory.zip

**Comment by xatnight** [comment] 2019-11-09 13:32
Downloaded around 60k files, no problem so far besides me reaching the rate limit for my imgur API. Using 8 threads, no deduplication.

**Comment by undertheblu3sky** [comment] 2019-11-10 02:18
It's not a dedup bug. While I think it happens more frequently with dedupe on. I have a thread right now with a database locked error without dedupe on. I'll try the rip above.

**Comment by shadowmoose** [comment] 2019-11-11 07:05
Okay, thanks everybody for testing. I'll plan on merging these changes tomorrow, unless I hear word that the bug is still popping up.

**Comment by undertheblu3sky** [comment] 2019-11-12 04:51
No more database bug. But was wondering if there were settings we could tweak having to do with dedupe? been sitting at 10,000+ files dedupe for like 12 hours. It's still working :) which is a great sign.  the number is decreasing. Just wondering if there could be a tweak setting to maybe speed or slow it down depending on processor cores or etc.

**Comment by shadowmoose** [comment] 2019-11-13 19:00
Splitting post-processing operations into multiple processes is something I'd like to support in the future, but it's a little trickier. Deduplication can use a lot of CPU - if allowed to use multiple cores - so I want to be sure it's implemented in a way that the user can fine-tune for performance.

This is probably the feature that the next major release (post-3.0.0) will be tackling.

**Comment by undertheblu3sky** [comment] 2019-11-13 20:32
I was actually thinking about maybe using a temp file to save the info, and then have it write to database in the background. I really wish I could program :>

**Comment by shadowmoose** [comment] 2020-01-15 02:39
Resolved as of [Release 3.0.0](https://github.com/shadowmoose/RedditDownloader/releases/tag/3.0.0). Feel free to reopen if this still needs more attention.

**Closed by shadowmoose** 2020-01-15 02:39 UTC
Labels: bug
