### ISSUE TITLE
Throws error if settings.json file is missing

### ISSUE THREAD

**Issue by aliparlakci** [shadowmoose/RedditDownloader#36] opened 2018-07-08 19:08 UTC
I installed the required packages and started up the code by going `python .\main.py` and got `prawcore.exceptions.ResponseException: received 401 HTTP response` error. I think the issue, before asking for my client_id and client_password, it tried to login to reddit. Here's the [console log](https://github.com/shadowmoose/RedditDownloader/files/2174023/log.txt), I hope you can fix the error.

Love from [bulk-downloader-for-reddit](https://github.com/aliparlakci/bulk-downloader-for-reddit).

**Comment by shadowmoose** [comment] 2018-07-08 20:44
Good catch! You're correct; that's likely caused by RMD attempting to sign into PRAW without first gathering user details. It seems I've forgotten to re-implement a bit of logic the old console Wizard provided. 

The latest branch is still a bit unstable with the fairly large changes, but that's certainly a bug which needs fixing before the next release.

Thanks for the report!

**Comment by shadowmoose** [comment] 2018-07-09 07:15
Fixed as of 5db75ed0de939b6cfd4c0e86806e223adc0ab8a5.

**Closed by shadowmoose** 2018-07-09 07:15 UTC
Labels: bug
