### ISSUE TITLE
"deduplicate files" setting not working

### ISSUE THREAD

**Issue by tayser1** [shadowmoose/RedditDownloader#48] opened 2019-01-04 00:27 UTC
The Setting under Output "deduplicate files" is not working for me correctly.
It doesn't detect duplicate and saves them all.

**Comment by shadowmoose** [comment] 2019-01-04 06:56
I'll need more information than that to debug what the issue is. Are the duplicate files images? If not, RMD can only detect non-image file duplicates if they are identical matches. 

Please provide more information. If they're small enough, can you provide two of the problematic files? Even their filenames/types would help.

**Comment by torchinz** [comment] 2019-01-08 15:13
I think, I am facing the same issue. Somehow, I am stuck with multiple duplicate of video files, despite of having checked the de-duplicate option in the UI. For e.g. I am having two videos of same 560MB sizes. The files names are 
1. Dr. Jordan B Peterson on Femsplainers - With Christina Hoff Sommers and Danielle Crittenden - (newplayer33554432) . 2.mp4
2. Dr. Jordan B Peterson on Femsplainers - With Christina Hoff Sommers and Danielle Crittenden - (newplayer33554432) . 3.mp4 

Actually, when I had ran RMD for the first time, the same video file had no number towards it end. But now, everytime I run RMD, the file is redownloaded with a renumbered version. 

Hope this helps you to debug shadowmoose. Love the creation :)

**Comment by torchinz** [comment] 2019-01-08 17:07
![ss](https://user-images.githubusercontent.com/17811608/50846738-dec4b900-1395-11e9-8f5b-7219a5994239.jpg)
Also, I am regularly getting this error. I have changed RMD to use Chrome instead of my default browser FF, but to no avail.

**Comment by shadowmoose** [comment] 2019-01-08 20:58
@torchinz That's a strange issue. Even if deduplication was disabled, it should never download from the same URL twice. Are you sure they're coming from the same post or link? If RMD is generating new copies of files from the same URLs whenever it runs, that's a deeper issue than the settings configuration.

**Comment by torchinz** [comment] 2019-01-09 04:12
Hi @shadowmoose . Unfortunately, yes. Initially, I checked if the links were getting updated or the reddit post were getting edited or something but none of that is happening here. The duplicated downloads are from the same post of the same subreddit. It is a duplicate download occuring every time.

**Comment by torchinz** [comment] 2019-01-11 12:15
Yes. The manifest.sqldb updates everytime RMD is executed. All the downloads are working fine but as mentioned, in certain instances, the duplicates are getting downloaded in the same folder from the same link/subreddit.

**Comment by shadowmoose** [comment] 2020-01-15 02:37
Resolved as of [Release 3.0.0](https://github.com/shadowmoose/RedditDownloader/releases/tag/3.0.0). Feel free to reopen if this still needs more attention.

**Closed by shadowmoose** 2020-01-15 02:37 UTC
