### ISSUE TITLE
RMD not downloading images from single-image imgur pages

### ISSUE THREAD

**Issue by brainless1012003** [shadowmoose/RedditDownloader#58] opened 2019-04-01 20:48 UTC
Getting the following error when RMD tries to download from imgur if its not a direct image link or an album:

     URL: https://imgur.com/nw33ENa
     Checking handler: imgur
             Imgur Error: URL must be a valid Imgur Album
     Checking handler: github
     Checking handler: reddit
     Checking handler: ytdl
             YTDL :: ERROR: No sources found for video nw33ENa. Maybe an image?
     Checking handler: newspaper
             "Newspaper" Generic handler failed. Configuration object being passed incorrectly as title or source_url! Please verify `Article`s __init__() fn.
     !No handlers were able to accept this URL.

It should be noted that I'm running an earlier version so if this was fixed in a later version, let me know what specific changes I need to make to the code.

**Comment by shadowmoose** [comment] 2019-04-02 05:35
Odd bug. This should be fixed in the next release, which is currently in testing before release.

As far as patching an older version, that might be tricky. The new version has significantly changed (and cleaned up) the Handlers for each site. The most recent version that should be backwards-compatible is here: https://github.com/shadowmoose/RedditDownloader/blob/legacy-threaded-3.0/classes/handlers/imgur.py

**Comment by brainless1012003** [comment] 2019-04-02 18:51
Fixing 'link' and 'href' worked somewhat, but its downloading as a .json file. 

        URL: https://imgur.com/znRDHYI
        !Incrementing duplicate filename. (5)
        Checking handler: imgur
                +Corrected Imgur URL: https://api.imgur.com/oembed.json?url=https://imgur.com/znRDHYI
        +Handler 'imgur' completed correctly! download\Sprik\Sprik . 5 .json

When I open the file it says:

    {"version":"1.0","type":"rich","provider_name":"Imgur","provider_url":"https:\/\/imgur.com","width":540,"height":500,"html":"<blockquote class=\"imgur-embed-pub\" lang=\"en\" data-id=\"znRDHYI\"><a href=\"https:\/\/imgur.com\/znRDHYI\">View post on imgur.com<\/a><\/blockquote><script async src=\"\/\/s.imgur.com\/min\/embed.js\" charset=\"utf-8\"><\/script>"}

**Comment by shadowmoose** [comment] 2019-04-12 22:56
The edit you made is not building the full, direct image link. The JSON file being downloaded is caused by RMD finding a link which it expects is a valid Image link, but is instead an Imgur API link. Off the top of my head, try something like:
```
			for u in stringutil.html_elements(req.text, 'link', 'href'):
				if base_img in u and 'api.' not in u:
					u = urllib.parse.urljoin('https://i.imgur.com/', u)
					print("\t\t+Corrected Imgur URL: %s" % u)
					url = u
```

**Closed** 2019-05-06 08:06 UTC
